

"""
Gaussian Process Emulator Training
===================================

This script trains Gaussian Process (GP) emulators for black hole population
statistics using PCA dimensionality reduction.

Pipeline Overview
-----------------
1. Load training data generated by make_training_data_new.py
2. For each quantity (QLF, BHMF, CERDF, QHMF):
   - Fit PCA to reduce dimensionality (auto-select n_components for 99.5% variance)
   - Train GP on PCA weights
   - Run cross-validation to assess emulator accuracy
   - Save PCA and GP models to disk

Emulator Outputs
----------------
- QLF: Quasar Luminosity Function φ(L)
- BHMF: Black Hole Mass Function φ(M_BH) (all BHs, no luminosity cut)
- CERDF: Conditional Eddington Ratio Distribution P(λ | L > L_thresh)
- QHMF: Quasar Host Halo Mass Function φ(M_halo | L > L_thresh)

Notes
-----
- Cross-validation reports errors in dex (log10 units)
- RMSE < 0.1 dex is considered excellent for astrophysical emulation
"""

# This module is a run script, not a library: its body loads catalogues and
# writes products at import time. Refuse a plain ``import`` so nobody starts a
# multi-hour job by accident (``python -m baqaro.emulation.main_emulation`` sets __name__ to
# "__main__"; a multiprocessing "spawn" child re-imports it as "__mp_main__").
if __name__ not in ("__main__", "__mp_main__"):
    raise RuntimeError(
        "baqaro.emulation.main_emulation is an entry-point script; run it with "
        "'python -m baqaro.emulation.main_emulation' instead of importing it."
    )


import os
import time
from matplotlib import pyplot as plt
import numpy as np

from baqaro.emulation.emulation_core_functions import GeneralEmulatorGP, GeneralEmulatorPCA

from baqaro.emulation.emulation_testing_helpers import check_parameter_scaling, diagnose_emulator_failure, hunt_cv_failure
from baqaro.utils.my_dir import get_output_path
from baqaro.emulation.loading_helpers import load_training_data
from baqaro.utils.sim_config import (
    FIDUCIAL_NOTES_TRAINING, FIDUCIAL_NOTES_EMULATION, FIDUCIAL_SMOOTH_TRAINING,
)



# ==========================================
# MAIN SCRIPT
# ==========================================

# 1. SETUP & LOAD DATA
# --------------------
# BASIC SETTINGS


# Module-level configuration
DEFAULT_SOURCE_DIR = os.environ.get("BAQARO_SOURCE_DIR", "machine_igm")  # site from the environment
source_dir = DEFAULT_SOURCE_DIR


# --- Run Identification ---
param_6d_mode = True  # If True, use the naming convention for the 6D parameter inference run

# Override via env vars so the same script works for L2800N5040 / L2800N10080
# without source edits.
# Fiducial notes-token defaults (sim_config.FIDUCIAL_NOTES_*) so a BARE run
# resolves to the adopted fiducial's training/emulator products with no env.
# An explicit BAQARO_NOTES_FILE_EMULATION wins; else an explicit _TRAINING is
# reused (legacy behaviour); else the fiducial emulation token (adds _smooth).
notes_file_training  = os.environ.get("BAQARO_NOTES_FILE_TRAINING") or FIDUCIAL_NOTES_TRAINING
notes_file_emulation = (os.environ.get("BAQARO_NOTES_FILE_EMULATION")
                        or os.environ.get("BAQARO_NOTES_FILE_TRAINING")
                        or FIDUCIAL_NOTES_EMULATION)

# --- Floor values ---
physical_floor = -9.5  # Threshold below which bins are considered empty
pca_floor = -10.  # Value assigned to empty bins for PCA training

# --- GP kernel ---
# Options: "matern32" (default, smooth), "matern52" (smoother), "matern12" (rough, sharp transitions)
kernel_type = "matern32"

# --- FILTERING TRAINING DATA ---
filter_training_data = True  # Whether  to filter out "bad" simulations

# --- Snapshot Range ---
min_snap = 0
from baqaro.utils.sim_config import max_snap

# --- Halo-data variant tokens (must match the training run filename) ---
from baqaro.utils.sim_config import fold_subhalo_mass, merger_delay_mode

# --- Subset tag (only meaningful when the training run used BAQARO_USE_SUBSAMPLE=1) ---
# Default below matches main_training.py's L2800N10080 maxsnap=60 fid3_10k run.
# Set BAQARO_SUBSET_TAG="" to load a full-sim (un-subsampled) training file.
# Default to the production subsampled run's tag (auto-derived from
# sim_config geometry + subsample env defaults) so callers needn't set
# BAQARO_SUBSET_TAG. Env presence wins: BAQARO_SUBSET_TAG="" => full-sim.
if "BAQARO_SUBSET_TAG" in os.environ:
    subset_tag = os.environ["BAQARO_SUBSET_TAG"]
else:
    from baqaro.core_functions.tree_subsample import resolve_subset_tag
    subset_tag = resolve_subset_tag(max_snap)


# --- ERDF (Eddington Ratio Distribution Function) ---
# Controls the distribution of accretion rates relative to Eddington
erdf_model = "log_normal_evol_halo_mass"


# --- Simulation Parameters ---
from baqaro.utils.sim_config import boxsize, N_particles_per_side, simulation_name


# Mirror the exact order that main_training.py uses to compose the
# output filename: maxsnap -> foldmass -> merger_delay_mode -> notes -> subset_tag.
name_file = "{}_erdf_{}_maxsnap_{}".format(
    simulation_name, erdf_model, max_snap
    )
if fold_subhalo_mass:
    name_file += "_foldmass"
if merger_delay_mode != "instant_old":
    name_file += "_{}".format(merger_delay_mode)


if notes_file_training is not None:
    name_file_training = name_file + "_{}".format(notes_file_training)
else:
    name_file_training = name_file

if notes_file_emulation is not None:
    name_file_emulation = name_file + "_{}".format(notes_file_emulation)
else:
    name_file_emulation = name_file

if subset_tag:
    name_file_training  += "_sub_{}".format(subset_tag)
    name_file_emulation += "_sub_{}".format(subset_tag)

# Growth-cap + madau-feff tokens (read from env), appended to BOTH the training
# and emulation names in the SAME order as main_training.py (_g before
# _feffcorr). Without these, an emulation run can neither find a capped/_feffcorr
# training file nor name its emulators distinctly from the uncapped/uncorrected ones.
# Single canonical home for the token logic: utils.sim_config.growth_feff_suffix.
from baqaro.utils.sim_config import growth_feff_suffix
_gf_suffix = growth_feff_suffix()
name_file_training  += _gf_suffix
name_file_emulation += _gf_suffix


path_out = get_output_path(source=source_dir)
path_emul_qlf = os.path.join(path_out, "emulators", f"emulator_qlf_{name_file_emulation}.xz")
path_pca_qlf = os.path.join(path_out, "emulators", f"pca_qlf_{name_file_emulation}.xz")

path_emul_bhmf = os.path.join(path_out, "emulators", f"emulator_bhmf_{name_file_emulation}.xz")
path_pca_bhmf = os.path.join(path_out, "emulators", f"pca_bhmf_{name_file_emulation}.xz")

path_emul_cerdf = os.path.join(path_out, "emulators", f"emulator_cerdf_{name_file_emulation}.xz")
path_pca_cerdf = os.path.join(path_out, "emulators", f"pca_cerdf_{name_file_emulation}.xz")

path_emul_qhmf = os.path.join(path_out, "emulators", f"emulator_qhmf_{name_file_emulation}.xz")
path_pca_qhmf = os.path.join(path_out, "emulators", f"pca_qhmf_{name_file_emulation}.xz")

path_file_training = os.path.join(path_out, "training", f"training_data_emulation_{name_file_training}.hdf5")


print("Loading data from", path_file_training)
data = load_training_data(path_file_training, physical_floor=physical_floor, pca_floor=pca_floor)
print("CATALOGUES LOADED")

# Data shapes from load_training_data:
# QLF:   (n_runs, n_z, n_lbins)
# BHMF:  (n_runs, n_z, n_mbins) — no L_threshold axis
# CERDF: (n_runs, n_z, n_Lthr, n_bins)
# QHMF:  (n_runs, n_z, n_Lthr, n_bins)
log_qlfs = data["log_qlfs"]
log_cerdfs = data["log_cerdfs"]
log_bhmfs = data["log_bhmfs"]
log_qhmfs = data["log_qhmfs"]

redshift_keys = data["redshift_keys"]  # shape: (n_redshift_keys,)
log_lbins = data["log_lbins"]        # shape: (n_lbins,)
log_bins_cerdf = data["log_bins_cerdf"]      # shape: (n_edd_bins,)
log_mbins_bhmf = data["log_mbins_bhmf"]  # shape: (n_mbins,)
log_mbins_qhmf = data["log_mbins_qhmf"]  # shape: (n_mbins,)
log_L_thresholds = data["log_L_thresholds"]  # shape: (n_L_thresh,)

params = data["params"]              # shape: (n_runs, n_params)
param_names = data["param_names"]  # list of parameter names
param_ranges = data["param_ranges"]  # shape: (n_params, 2)


# Data already in sample-first format: (n_runs, ...)
log_qlfs_sim_first = log_qlfs  # (n_runs, n_z, n_lbins)
log_cerdfs_sim_first = log_cerdfs  # (n_runs, n_z, n_Lthr, n_bins)
log_bhmfs_sim_first = log_bhmfs  # (n_runs, n_z, n_mbins)
log_qhmfs_sim_first = log_qhmfs  # (n_runs, n_z, n_Lthr, n_bins)

name_emulators = ["QLF", "CERDF", "BHMF", "QHMF"]
all_data_arrays = [log_qlfs_sim_first, log_cerdfs_sim_first, log_bhmfs_sim_first, log_qhmfs_sim_first]
all_bin_arrays = [log_lbins, log_bins_cerdf, log_mbins_bhmf, log_mbins_qhmf]
paths_emulators = [path_emul_qlf, path_emul_cerdf, path_emul_bhmf, path_emul_qhmf]
paths_pca = [path_pca_qlf, path_pca_cerdf, path_pca_bhmf, path_pca_qhmf]



# --- FILTER: REMOVE "MOSTLY EMPTY" AND "BAD" SIMULATIONS (Flexible) ---

if filter_training_data:
    print("\n--- FILTERING BAD SIMULATIONS ---")


    # --- STEP 1: IDENTIFY BAD INDICES GLOBALLY ---
    bad_indices_global = []

    # List all data arrays you plan to loop over
    # (Make sure these are the raw, full-size arrays)

    # NB: loop var is `arr`, NOT `data` — `data` is the training-data dict
    # (loaded above, its arrays already unpacked); reusing it as the loop var
    # would silently rebind the dict to the last array.
    for arr, name in zip(all_data_arrays, name_emulators):
        # Check data quality
        print(f"\n{name}:")
        global_floor_fraction = np.mean(arr <= physical_floor+0.1)
        print(f"  Fraction of floored values: {global_floor_fraction:.2%}")
        print(f"  Min/Max non-floor values: {arr[arr > physical_floor+0.1].min():.2f}, {arr.max():.2f}")

        # Per-simulation emptiness (single computation — the earlier duplicate
        # was dead, overwritten before use).
        emptiness = np.mean(arr.reshape(arr.shape[0], -1) <= physical_floor+0.1, axis=1)
        n_bad = np.sum(emptiness > 0.8)
        print(f"  Sims with >80% empty: {n_bad} / {len(emptiness)}")
        
        # Skip this array from filtering if it's globally problematic (>95% floored overall)
        if global_floor_fraction > 0.95:
            print(f"  ⚠️  Skipping {name} from filtering (globally floored: {global_floor_fraction:.1%})")
            continue
        
        # 2. Find bad indices for this array
        bad_idx = np.where(emptiness > 0.80)[0]
        bad_indices_global.extend(bad_idx)


    # 3. Get the unique list of "bad" simulations
    unique_bad_indices = np.unique(bad_indices_global)

    print(f"\nGLOBALLY removing {len(unique_bad_indices)} simulations")
    if len(unique_bad_indices) > 0 and len(unique_bad_indices) < 20:
        print(f"  Bad indices: {unique_bad_indices}")

    # --- STEP 2: FILTER EVERYTHING ONCE ---
    mask = np.ones(params.shape[0], dtype=bool)
    mask[unique_bad_indices] = False

    # Permanently filter the global variables
    params = params[mask]
    log_qlfs_sim_first = log_qlfs_sim_first[mask]
    log_cerdfs_sim_first = log_cerdfs_sim_first[mask]
    log_bhmfs_sim_first = log_bhmfs_sim_first[mask]
    log_qhmfs_sim_first = log_qhmfs_sim_first[mask]
    
    print(f"Remaining simulations after filtering: {params.shape[0]}")

all_data_arrays_cleaned = [log_qlfs_sim_first, log_cerdfs_sim_first, log_bhmfs_sim_first, log_qhmfs_sim_first]


# 2. TRAIN EMULATORS


# Resume support: skip any emulator whose final `.xz` is already on disk.
# Useful when the previous run died part-way through (e.g. silent SIGKILL
# during CV) — just re-run and we'll pick up where we left off. Set the
# env var BAQARO_RETRAIN_ALL=1 to force a full retrain ignoring saved
# files; default keeps the resume behavior.
_force_retrain = os.environ.get("BAQARO_RETRAIN_ALL", "0") == "1"

# Skip cross-validation during fitting: set BAQARO_SKIP_CV=1 to only fit +
# save the four emulators (fast). Run CV separately afterwards with
# `python -m baqaro.emulation.cross_validate_emulators`, which
# reproduces the exact same load/filter/PCA setup and reports per-quantity
# RMSE without refitting the saved final emulators.
_skip_cv = os.environ.get("BAQARO_SKIP_CV", "0") == "1"

# Restrict to a subset of quantities: BAQARO_EMUL_ONLY=qlf  (or comma-sep,
# case-insensitive). Lets the four independent emulator fits run as separate
# parallel processes (one quantity each). Empty/unset = fit all four.
_emul_only = {s.strip().lower() for s in os.environ.get("BAQARO_EMUL_ONLY", "").split(",") if s.strip()}

for quantity, log_bins, path_emu, path_pca, name in zip(
    all_data_arrays_cleaned[:],
    all_bin_arrays[:],
    paths_emulators[:],
    paths_pca[:],
    name_emulators[:]
    ):

    if _emul_only and name.lower() not in _emul_only:
        continue

    if (not _force_retrain) and os.path.exists(path_emu):
        print(f"\n{'='*50}\n{name}: emulator already on disk at {path_emu!r} — SKIPPING.")
        print(f"  (set BAQARO_RETRAIN_ALL=1 to force re-training)")
        continue

    # Optional Savitzky-Golay denoising of the TRAINING data before PCA/GP
    # (mode "1a"): removes subsample shot noise so the PCA basis isn't
    # contaminated and the reported CV RMSE reflects true accuracy rather than
    # target noise. Per-quantity (window, poly) validated on full-sim L5040
    # truth: monotonic QLF/BHMF use SG(7,2); peaked QHMF/CERDF use the gentler
    # SG(5,3) (SG(7,2) clips the CERDF peak by -0.036 dex). Now ON by default
    # (sim_config.FIDUCIAL_SMOOTH_TRAINING) — the fiducial emulators are
    # _smooth; set BAQARO_SMOOTH_TRAINING=0 for the raw (legacy) path.
    if os.environ.get("BAQARO_SMOOTH_TRAINING",
                      "1" if FIDUCIAL_SMOOTH_TRAINING else "0") == "1":
        from baqaro.emulation.sg_smoothing import (
            smooth_function_rows, SG_PARAMS_BY_QUANTITY,
        )
        _w, _p = SG_PARAMS_BY_QUANTITY.get(name.lower(), (7, 2))
        quantity = smooth_function_rows(quantity, _w, _p, floor=pca_floor)
        print(f"{name}: SG-smoothed training data before fit (window={_w}, poly={_p})")

    axis_info = {
    "redshift": redshift_keys,
    "log_L_threshold": log_L_thresholds,
    "log_bins": log_bins
    }


    print(f"{name} Data Shape: {quantity.shape} (Sims, Redshifts, Bins...)")

    # --- PCA: Fit once with max components, then select optimal n ---
    print("\n--- PCA Variance Analysis ---")
    time_pca_start = time.time()
    
    # Fit PCA with enough components to analyze variance.
    # Cap default 15: an n_components CV sweep
    # showed every quantity is interpolation-limited
    # and plateaus by n<=15 (QLF ~6, QHMF ~10, BHMF/CERDF ~15); components
    # 15-30 add no CV-RMSE gain, only cost — and for CERDF the noisy tail
    # grows the worst-case error. Override via BAQARO_MAX_PCA_COMPONENTS.
    _max_pca = int(os.environ.get("BAQARO_MAX_PCA_COMPONENTS", "15"))
    max_components = min(_max_pca, quantity.shape[0] - 1)  # Can't exceed n_samples - 1
    emu_pca = GeneralEmulatorPCA(n_components=max_components, floor_value=pca_floor)
    emu_pca.fit(quantity)

    print(f"\nVariance explained by each component:")
    for i, var in enumerate(emu_pca.pca.explained_variance_ratio_[:max_components]):
        cumvar = np.sum(emu_pca.pca.explained_variance_ratio_[:i+1])
        print(f"  PC {i+1:2d}: {var:6.4f} (cumulative: {cumvar:.4f})")

    # Choose n_components based on cumulative variance (aim for >99.8%)
    cumsum = np.cumsum(emu_pca.pca.explained_variance_ratio_)
    if np.any(cumsum > 0.998):
        optimal_n = np.argmax(cumsum > 0.998) + 1
    else:
        optimal_n = max_components  # fallback if threshold not reached
    print(f"\nOptimal n_components for 99.8% variance: {optimal_n}")

    # Refit with optimal number of components (required for correct transform)
    emu_pca = GeneralEmulatorPCA(n_components=optimal_n, floor_value=pca_floor)
    training_weights = emu_pca.fit_transform(quantity)
    
    print(f"PCA completed in {time.time() - time_pca_start:.2f} seconds.")
    print(f"Variance explained by top {optimal_n} components: {np.sum(emu_pca.pca.explained_variance_ratio_):.3f}")

    print("Saving PCA model...")
    emu_pca.save(path_pca)
    print(f"PCA model saved successfully to {path_pca}")


    # B. TRAIN THE GP
    # --------------------

    print("\n--- Starting GP Training ---")

    time_here = time.time()

    # 1. Prepare Axis Data 


    print("Training GP on raw parameters...")
    # 2. Initialize GP
    emu_gp = GeneralEmulatorGP(
        pca_model=emu_pca,
        param_names=param_names,
        param_ranges=param_ranges,
        axis_data=axis_info,
        kernel_type=kernel_type,
        verbose=True
    )



# Run 5-fold CV before final training, unless BAQARO_SKIP_CV=1 (fit-only).
    if _skip_cv:
        print("Skipping cross-validation (BAQARO_SKIP_CV=1) — fit + save only.")
    else:
        print("Running 5-Fold Cross-Validation (Physical Space)...")

        target_data_for_cv = quantity

        try:
            cv_results = emu_gp.cross_validate_physical(
                params,
                training_weights,
                Y_physical=target_data_for_cv,
                k_folds=5,
                normalize_params=True,
                verbose=True,
                real_threshold=physical_floor
            )
            print(f"Type of cv_results: {type(cv_results)}")
        except Exception as e:
            print(f"ERROR during cross_validate_physical: {e}")
            import traceback
            traceback.print_exc()
            raise

        print(f"Cross-Validation completed in {time.time() - time_here:.2f} seconds.")
        print("\n--- PHYSICAL VALIDATION RESULTS ---")

        if cv_results is not None:
            # Extract Physical Metrics
            # These keys assume your new function returns 'rmse_physical' and 'max_error_physical'
            rmse_dex = cv_results.get('rmse_physical', -1)
            median_ae_dex = cv_results.get('median_ae_physical', -1)
            max_err = cv_results.get('max_error_physical', -1)

            # Print Key Scientific Metrics
            print(f"Global RMSE:      {rmse_dex:.4f} dex (Average error across all bins)")
            print(f"Median Abs Error: {median_ae_dex:.4f} dex (Robust to outliers)")
            print(f"Max Outlier:      {max_err:.4f} dex (Worst single prediction error)")

            # --- Interpretation of Scientific Quality ---
            # 0.1 dex is a standard threshold for "good" astrophysical emulation
            if rmse_dex < 0.05:
                print("\n✅ EXCELLENT: Error < 0.05 dex. High-precision emulation achieved.")
            elif rmse_dex < 0.15:
                print(f"\n✅ GOOD: Error {rmse_dex:.3f} dex. Suitable for standard inference.")
            elif rmse_dex < 0.30:
                print(f"\n⚠️  FAIR: Error {rmse_dex:.3f} dex. Check if sufficient for your science case.")
            else:
                print(f"\n❌ POOR: Error {rmse_dex:.3f} dex. Emulator is struggling. Check training data or outliers.")

            hunt_cv_failure(cv_results, floor_value=pca_floor, real_threshold=physical_floor)

        else:
            print("WARNING: cv_results is None, skipping diagnostics!")
    
    
    
    # 3. Final Training on Full Dataset
    # --- Final GP Fit ---
    print("\nTraining GP on normalized parameters...")
    time_gp_start = time.time()
    emu_gp.fit(params, training_weights)
    print(f"GP Training completed in {time.time() - time_gp_start:.2f} seconds.")


    # 3. RUN DIAGNOSTICS
    check_parameter_scaling(params)
    diagnose_emulator_failure(emu_pca, emu_gp, params, quantity)

    # Save just ONE file
    # The internal scaler (self.scaler) is already attached automatically by fit()
    emu_gp.save(path_emu)

    print(f"Emulator saved successfully to {path_emu}")

    print("\n" + "="*50 + "\n")

plt.show()